### ISSUE TITLE
Web endpoint for external scraping

### ISSUE THREAD

**Issue by ethanfrogers** [Netflix/spectator-go#38]
Hello! I'm not sure how often anyone looks as this repo but I figured I'd post anyway. 

I'm curious if anyone would fine the need for exposing a web endpoint in this package like the JVM library does. My use case is this - I work on Spinnaker for a company called Armory and we have an service that is written in Go and is shipped alongside the OSS version of Spinnaker. We'd like to fall into the monitoring patterns that the rest of the OSS ecosystem follows. In order to match what the JVM services are doing, we want to expose an endpoint at `/spectator/metrics` that can be scraped by a sidecar that we deploy alongside each instance. I've had some trouble implementing this in my application as a standalone (Registry URI points to an in-process HTTP server) so I was wondering if we could simply make it a first class pattern in this library. 

I'm happy to implement this myself if it's something you're willing to accept!

**Comment by brharrington** [comment]
Hello, we do watch the repo.

I'm not sure it is a good fit for this project, but am open to considering it. Some initial thoughts and context:

The Java `spectator-web-spring` library was to help them integrate with Stackdriver, though looking quickly now I couldn't find a spec for the /metrics endpoint that library produces so I'm not sure it is really a Stackdriver standard. From talking with our internal teams supporting Spinnaker, their plan is to gradually move to [Micrometer](https://micrometer.io/) since Spinnaker is Spring based anyway. Micrometer and Spectator are pretty similar, the original author was formerly at Netflix and borrowed a lot, but they are more incentivized for supporting many metrics backends. We have a bias to internal use-cases at Netflix and focus mostly on Atlas. Micrometer also uses Spectator for the Atlas registry implementation.

There is a `spectator-reg-micrometer` for Java that can be used to map the data going to Spectator to Micrometer and thus to whatever backends Micrometer has integrations with. I'm not sure the status, but I think there is some work being looked at to set this up for Spinnaker in the short term as an intermediate step.

Assuming this was there, then you could pick an integration for Spinnaker and just use a corresponding integration for your Go library, for example, if you used Prometheus you could just use the [Prometheus Go Client](https://github.com/prometheus/client_golang).

**Comment by ethanfrogers** [comment]
Thanks for following up! I spoke with Rob Zienert about this last week and he mentioned Micrometer as well. I was hoping to find an intermediate solution while it's being introduced. For now, I may just stick with Prometheus for internal telemetry and explore other options for integrating with the rest of Spinnaker's monitoring stack. Thanks again!
